### ISSUE TITLE
Does it support union operation ,removing duplicate entries

### ISSUE THREAD

**Issue by Eldadc** [GeorgDangl/CoberturaConverter#5]
Hi,

My goal is to merge two different coverage coberuta xml report , one was created with OpenCPPCoverage and the other with gcovr ( Code coverage by GNU GCC).
The issue is that on one report some files are been covered and on the other report they are not covered , but for developers it is ok that at least on one Testing program cover a file.

We have two different cobertura xml files ,
One of the xml is done by cppopencoverage and one is done by gcovr.
The me

How can I merge two xml as union ?
I have slimier files that are on different packages, If on OpenCPPCoverage xml a file was covered 100% and on the other report generated by gcovr is 0% , The merge will not point on the 100% cover. It just add the files on different package with coverage percentage. 
Of course the reports are different in term of breakdown of packages.

How can I tackle such issue from your experience ?
Hope you understand my question.

Thanks

**Comment by GeorgDangl** [comment]
Hi @Eldadc, thank you for the question!

Right now, the converter doesn't do any of these things - neither a merge, nor a removal of duplicates. However, I actually happen to have done something similar, when merging test results from different frameworks. You could take a look at it here: https://github.com/GeorgDangl/LightQuery/blob/dev/build/Build.cs#L314-L340

It just boils down to writing some code to do the actual merge. The most amount will probably be required for 1) identifying which nodes should be merged and 2) the actual merge logic, so that the results do add up.

I'd happily accept a PR if you come around to do that😊

**Comment by Eldadc** [comment]
Thanks on the help and tip.
